## Question

Write a NumPy program that creates a 3x3 matrix of random integers between 0 and 9 and prints the maximum and minimum values of the matrix.

## Answer:

In [26]:
import numpy as np

arr = np.random.randint(0, 10, size = (3,3))
print(arr)

[[4 4 5]
 [6 1 1]
 [6 4 7]]


So, in the **random.randint(**the range of the number you wish to generate,** **size = (Array size)**)**

### To print Max:

We can use the **np.max()** function to find the maximum value in a given array

In [27]:
max = np.max(arr)
print(max)

7


### To print Min:
We can use the **np.min()** fucntion to find the minimum value in a given array

In [28]:
min = np.min(arr)
print(min)

1
