### Question 
Write a NumPy program that creates a 5x5 identity matrix and replaces the diagonal elements with random integers between 0 and 9.

### Answer:

In [10]:
import numpy as np

# creates an identity 5x5 matrix 
arr1 = np.eye(5)

# creates a 5*5 array with random integer between 0 and 9
arr2 = np.random.randint(0, 10, size=(5, 5))

# multiplies both array to replace diagonal elements with random integer between 0 and 9
result = arr1*arr2
print(result)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 9.]]


The above was my method, now trying the **tutor's method**

In [12]:
matrix = np.eye(5)
random_numbers = np.random.randint(0, 10, size=(5,5))

# replace the diagonal elements of the identity matrix with the random integers
np.fill_diagonal(matrix, random_numbers)
print("Modified matrix:\n", matrix)

Modified matrix:
 [[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 2.]]
