# Creating and Displaying 2D Array

In [9]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


**You can print the array row by row using for loop**

In [10]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]
