# Shape and Reshape of Array

when using the **Shape** attribute or function, you get the shape of the array in (row, column) format

In [7]:
import numpy as np
arr1 = np.array([12, 12, 45])
arr2 = np.array([[12, 56, 78, 77], [24, 45, 67, 78], [24, 256, 78, 89]])
arr3 = np.array([[33, 33, 33], [34, 6, 6]])

In [8]:
attr1 = arr1.shape
attr2 = arr2.shape
attr3 = arr3.shape

print(f"The shape of the arr1 is: {attr1} \nThe shape of the arr2 is: {attr2} \nThe shape of the arr3 is: {attr3}")

The shape of the arr1 is: (3,) 
The shape of the arr2 is: (3, 4) 
The shape of the arr3 is: (2, 3)


Note: When it's just one row or a one dimensional array, the **shape** attribute just outputs the column since it's already a single row

Using the **Reshape** attribute or function, helps you reshape the array in terms of rows and columns

So I want to reshape all the Arrays above.

In [13]:
arr1 = arr1.reshape(3,1)
arr2 = arr2.reshape(2, 6)
arr3 = arr3.reshape(3, 2)

In [15]:
print("New shape for Arr1:", arr1.shape)

New shape for Arr1: (3, 1)


In [16]:
print("New shape for Arr2:", arr2.shape)
print("New shape for Arr3:", arr3.shape)

New shape for Arr2: (2, 6)
New shape for Arr3: (3, 2)


In [17]:
print(arr1)

[[12]
 [12]
 [45]]


In [18]:
print(arr2)

[[ 12  56  78  77  24  45]
 [ 67  78  24 256  78  89]]


In [19]:
print(arr3)

[[33 33]
 [33 34]
 [ 6  6]]
