# Random Matrix

Similar to the generation of Random Array, you use the random.rand() function. But this time, you imput the shape of the matrix. Also,it generates between 0 and 1

In [1]:
import numpy as np
arr = np.random.rand(3,4)
print(arr)

[[0.2863183  0.9578565  0.25986962 0.46032248]
 [0.76384066 0.84608365 0.71385568 0.60572219]
 [0.41420291 0.08853678 0.27707253 0.99972209]]
