# Creation of a Diagonal Matrix

In [2]:
import numpy as np
arr = np.diag([1, 2, 3, 4])

Those elements inside the function are the elements that I want to be the diagonal of the matrix. Also, the number of the elements determines the shape of the matrix. This is going to be a 4*4 matrix

In [3]:
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
