# Stacking

 Stacking means to join two or more arrays, either horizontally or vertically, meaning that it is done along a new axis.
 They are of different types

- `np.vstack()` stacks vertically
- `np.hstack()` stacks horizontally
- `np.hsplit()` splits the array into smaller parts

In [7]:
import numpy as np

arr1 = np.array([[2,5],[8,6]])
arr2 = np.array([[7,4],[3,2]])
print(f'arr1:\n{arr1}')
print(f'arr2:\n{arr2}')

arr1:
[[2 5]
 [8 6]]
arr2:
[[7 4]
 [3 2]]


In [5]:
# To stack the arrays vertically:

vert_stacking = np.vstack((arr1, arr2))
print(vert_stacking)

[[2 5]
 [8 6]
 [7 4]
 [3 2]]


In [6]:
# To stack the array horizontally:

horz_stacking = np.hstack((arr1, arr2))
print(horz_stacking)

[[2 5 7 4]
 [8 6 3 2]]


In [10]:
# To split the arrays into smaller parts

to_split = np.hsplit(horz_stacking, (2,2))
print(to_split)

[array([[2, 5],
       [8, 6]]), array([], shape=(2, 0), dtype=int32), array([[7, 4],
       [3, 2]])]
