# Mathematical Operations on Array

Mathematical operations such as addition, subtraction, multiplaction can be performed on arrays

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


**Addition**

In [2]:
arr = arr + 5
print(arr)

[ 6  7  8  9 10]


**Subtraction**

In [3]:
arr = arr - 5
print(arr)

[1 2 3 4 5]


**Multiplication**

In [4]:
arr = arr * 5
print(arr)

[ 5 10 15 20 25]


**Division**

In [6]:
arr = arr / 5
print(arr)

[1. 2. 3. 4. 5.]
